---
name: 'Supported Ruby Versions'
description: 'Output a list of supported Ruby versions. Intended for use as a Matrix strategy by other workflows.'

inputs:
  minimum_version:
    description: 'The minimum Ruby version to include in the output.'
    required: false
    default: '3.1'

outputs:
  supported_versions:
    description: 'The list of supported Ruby versions.'
    value: ${{ steps.script.outputs.supported_versions }}

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
  - id: script
    env:
      MINIMUM_VERSION: ${{ inputs.minimum_version }}
    run: ${{ github.action_path }}/bin/supported_ruby_versions
    shell: bash
