---
# Need to manually verify the output of the action for now
# TODO: Add automated test assertions
name: Test
on: push
jobs:
  # Test the default inputs
  ruby-versions-default:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.supported_versions }}
    steps:
    - uses: actions/checkout@v4
    - id: versions
      uses: ./
  
  test-defaults:
    runs-on: ubuntu-latest
    needs: ruby-versions-default
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions-default.outputs.versions) }}
    steps:
    - run: echo ${{ matrix.ruby }}
  
  # Test the minimum version setting input
  ruby-versions-requirement:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.supported_versions }}
    steps:
    - uses: actions/checkout@v4
    - id: versions
      uses: ./
      with:
        version_requirement: ">= 3.2"

  test-versions-requirement:
    runs-on: ubuntu-latest
    needs: ruby-versions-requirement
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions-requirement.outputs.versions) }}
    steps:
    - run: echo ${{ matrix.ruby }}
